const C=require('./ema-charts.js'),V=require('./ema-view.js');
const {num:n,pct:p,signed,esc}=V;
const head=(label,title,intro)=>`<div class="lab-head"><p class="lab-label">${label}</p><h3>${title}</h3><p class="lab-intro">${intro}</p></div>`;
const slider=(id,label,value,min,max,step,output,note)=>`<label class="control" for="${id}"><span class="control-label"><span>${label}</span><output id="${id}-out" for="${id}">${output}</output></span><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"/><small>${note}</small>${['win-rate','avg-win','avg-loss'].includes(id)?`<input type="number" class="number-control" id="${id}-number" aria-label="${label} กรอกตัวเลข" min="${min}" max="${max}" step="any" value="${Number(value).toFixed(2)}"/>`:''}</label>`;
const chart=(id,content,label)=>`<div id="${id}" class="chart-scroller" tabindex="0" role="region" aria-label="${label} เลื่อนแนวนอนได้">${content}</div>`;
const status=id=>`<p class="visually-hidden" role="status" aria-live="polite" id="${id}-status"></p>`;
const table=(heads,rows)=>`<div class="table-scroll" tabindex="0" role="region" aria-label="สมุดรายการซื้อขาย"><table><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((v,i)=>`<td${i?' class="numeric"':''}>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
module.exports=function(r,data){
 const t=r.tradeMetrics,pm=r.portfolioMetrics,bars=V.normalize(data),first=r.tradeLedger[0],signalTrade=r.tradeLedger[1]||first;
 const date=i=>i?r.dailyEquity[i-1].date:r.parameters.startDate+' ก่อนเปิด';
 const trades=table(['เทรด','วันซื้อ–ขาย','ก่อนต้นทุน (USD)','ต้นทุน (USD)','สุทธิ (USD)'],r.tradeLedger.map(t=>[t.id,`${t.entryTime} → ${t.exitTime}`,signed(t.grossPnl),n(t.totalFees),signed(t.netPnl)]));
 const questions=[
 ['ชนะน้อยกว่าครึ่ง ทำไมยังมีกำไร',`ชนะ ${n(t.wins,0)} จาก ${n(t.count,0)} เทรด แต่กำไรเฉลี่ย ${n(t.averageWin)} USD สูงกว่าขาดทุนเฉลี่ย ${n(t.averageLoss)} USD จึงได้ Expectancy ${signed(t.expectancy)} USD`],
 ['EMA 20/200 ใช้ราคาอะไร','ราคาปิดรายวัน 20 และ 200 เป็นช่วงวันของ EMA ตรวจสัญญาณหลังตลาดปิด แล้วซื้อขายที่ราคาเปิดวันถัดไป'],
 ['CAGR ต่างจาก Total Return อย่างไร','Total Return วัดผลสะสมทั้งช่วง ส่วน CAGR ใช้ระยะเวลา 7,304 วันปฏิทินหาร 365.25 เพื่อแปลงเป็นการเติบโตทบต้นต่อปี'],
 ['Drawdown ฟื้นครบหรือยัง',`ช่วง MDD ฟื้นถึงยอดเดิมวันที่ ${date(pm.maxDrawdownRecoveryIndex)} ใช้ ${pm.peakToRecoveryPeriods} วันซื้อขายจากยอด และ ${pm.troughToRecoveryPeriods} วันจากจุดต่ำสุด ส่วนช่วงล่าสุด ณ สิ้นข้อมูลยังต่ำกว่ายอดมา ${pm.underwaterPeriodsToEnd} วัน`],
 ['ชนะ Benchmark พร้อมใช้จริงหรือยัง','ยังสรุปไม่ได้ ต้องทดสอบนอกตัวอย่างและใช้ราคา ต้นทุน และข้อจำกัดของเครื่องมือที่ซื้อขายได้จริง ดัชนีราคาในบทนี้ไม่รวมเงินปันผล']
 ];
 return {
 'report-reader':`<section class="lab report-reader" id="read-report" aria-label="ฝึกอ่านรายงาน Backtest">${head('รายงานผล · S&P 500 ปี 2006–2026','รายงานเดียว ตอบทั้งผลตอบแทน ความเสี่ยง และผลการซื้อขาย','เริ่มอ่าน Total Return แล้วกด Win Rate และ Expectancy เพื่อดูว่าทำไมชนะน้อยกว่าครึ่ง แต่พอร์ตมีกำไร เลือกกลุ่มเพื่ออ่านทีละเรื่อง')}<div class="report-toolbar"><label for="metric-group">แสดงตัวชี้วัด</label><select id="metric-group"><option value="all">ทุกกลุ่ม</option><option value="return">ผลตอบแทนพอร์ต</option><option value="risk">ความเสี่ยงของพอร์ต</option><option value="trade">ผลรายเทรดและต้นทุน</option></select><span>${n(pm.periods,0)} วันซื้อขาย · ${r.parameters.startDate} ถึง ${r.parameters.endDate} · หลังต้นทุน · RF = MAR = 0%</span></div>${V.reportTable(r)}<div id="metric-help" class="lab-explanation" aria-live="polite">${V.metricHelp(r,'totalReturn')}</div><p class="lab-foot">Benchmark ถือ S&P 500 Price Index ตั้งแต่ต้นจนจบตามแบบจำลอง ใช้ทุนและอัตราต้นทุนเดียวกัน เครื่องหมาย — หมายถึงไม่ได้ใช้สถิติรายเทรดของ Benchmark ในตารางนี้ กดชื่อแถวเพื่ออ่านความหมายและข้อควรระวัง</p></section>`,
 'ema-lab':`<section class="lab" aria-label="สัญญาณ EMA และจังหวะซื้อขาย">${head('ภาพที่ 1 · จากราคาสู่คำสั่ง','เส้นตัดตอนแท่งปิด ซื้อที่แท่งถัดไป','เริ่มที่สัญญาณซื้อ T2 ซึ่งเป็นการตัดขึ้นในช่วงทดสอบ กด “แท่งถัดไป” เพื่อเห็นราคาที่ใช้ซื้อ แถบด้านล่างแสดงเป้าหมายจากสัญญาณแท่งก่อนหน้า')}<div class="controls two">${slider('signal-bar','เลือกแท่งราคา',signalTrade.entryDecisionBar,r.parameters.warmupBars-1,bars.length-1,1,V.barLabel(bars[signalTrade.entryDecisionBar]),'หมายเลขแท่งรวมช่วงเตรียม EMA แล้ว') }<label class="control" for="signal-event"><span class="control-label">ไปยังจังหวะสำคัญ</span><select id="signal-event">${[['สัญญาณซื้อ T2',signalTrade.entryDecisionBar],['สัญญาณขาย T2',signalTrade.exitDecisionBar],['วันสุดท้ายและการปิดบังคับ',bars.length-1]].map(([x,v])=>`<option value="${v}">${x}</option>`).join('')}</select><small>ราคาเป็นจุดดัชนี S&P 500; การส่งคำสั่งเป็นแบบจำลอง</small></label></div><div class="lab-body">${chart('signal-chart',C.signal(bars,signalTrade.entryDecisionBar),'S&P 500 EMA 20 EMA 200 และเป้าหมายถือครอง')}<div id="signal-detail" class="month-detail"></div></div><div class="lab-actions"><button id="bar-back" type="button">แท่งก่อน</button><button id="bar-next" type="button">แท่งถัดไป</button></div><p class="lab-foot">20 และ 200 หมายถึงช่วง 20 วันและ 200 วัน ใช้ข้อมูลปิดแท่งที่รู้แล้วเท่านั้น เป้าหมาย 100% ถือสินทรัพย์ หรือ 0% ถือเงินสด ไม่มีการขายทิ้งตามเวลาปิดวัน</p>${status('signal')}</section>`,
 'trade-lab':`<section class="lab" aria-label="ตรวจผลการซื้อขายทีละเทรด">${head('ภาพที่ 2 · ผลของการซื้อแล้วขายหนึ่งรอบ','เทรดชนะน้อยครั้ง แต่กำไรเฉลี่ยมากกว่า','เลือกเทรดที่ 1 แล้วเทียบกับเทรดที่ 2 ทุกแท่งแสดงกำไรขาดทุนหลังต้นทุนของหนึ่งรอบซื้อขาย')}<div class="controls two">${slider('trade-index','เลือกเทรด',1,1,t.count,1,'T1','ดูราคาซื้อ ราคาขาย และต้นทุนจากสมุดรายการ')}</div><div class="lab-body">${chart('trade-chart',C.tradeBars(r.tradeLedger,0),`กำไรขาดทุนสุทธิทั้ง ${t.count} เทรด`)}<div id="trade-detail" class="month-detail"></div></div><details class="data-details"><summary>เปิดสมุดรายการครบ ${t.count} เทรด</summary>${trades}</details>${status('trade')}</section>`,
 'distribution-lab':`<section class="lab" id="trade-distribution" aria-label="การแจกแจงกำไรขาดทุนสุทธิรายเทรด">${head('ภาพ · การกระจายของผลรายเทรด','กำไรขาดทุนส่วนใหญ่กระจุกอยู่ช่วงใด','แท่งนับจำนวนเทรดในแต่ละช่วงกำไรขาดทุน ส่วนจุดแสดงผลของแต่ละไม้ เลือกเทรดเพื่อดูตำแหน่งและจำนวนเงินจริง')}<div class="controls two">${slider('distribution-index','เลือกเทรดในกราฟการแจกแจง',1,1,t.count,1,'T1','จุดทั้งหมดใช้ข้อมูลเดียวกับสมุดรายการ ไม่เรียงตามเวลา')}</div><div class="lab-body">${chart('distribution-chart',C.tradeDistribution(r.tradeLedger,0),'การแจกแจงกำไรขาดทุนสุทธิ USD และจุดทั้ง 19 เทรด')}<div id="distribution-detail" class="month-detail"></div></div><p class="lab-foot">กำไรอยู่ขวาของศูนย์ ขาดทุนอยู่ซ้าย เส้น Average Loss แสดงที่ −${n(t.averageLoss)} USD ส่วนรายงานบอกขนาดที่เสียเป็น +${n(t.averageLoss)} USD เทรด T19 ปิดเมื่อสิ้นข้อมูลตามกติกา</p>${status('distribution')}</section>`,
 'drawdown-period-lab':`<section class="lab" id="drawdown-duration" aria-label="ระยะเวลาลดลง ฟื้นตัว และต่ำกว่ายอดเดิม">${head('ภาพ · ระยะเวลาของช่วง Maximum Drawdown','425 วันลดลง แล้วใช้ 432 วันกลับถึงยอดเดิม','ขยายเฉพาะช่วง MDD ของ EMA เพื่ออ่านวันที่ยอดเดิม จุดต่ำสุด และวันแรกที่กลับถึงยอดเดิม ความยาวแถบด้านล่างใช้จำนวนวันซื้อขายจริง')}<div class="lab-body">${chart('drawdown-period-chart',C.drawdownEpisode(r.dailyEquity,r.parameters.initialEquity,pm),'ช่วง Drawdown Recovery และ Underwater ของ EMA')}</div><div class="lab-explanation"><p>Drawdown period ${pm.maxDrawdownTroughIndex-pm.maxDrawdownPeakIndex} วัน + Recovery period ${pm.troughToRecoveryPeriods} วัน = Underwater period ${pm.peakToRecoveryPeriods} วันซื้อขาย นับระยะห่างของวันเริ่มและวันสิ้นสุด ไม่บวกวันเริ่มซ้ำ</p></div><p class="lab-foot">คำเรียกอาจต่างกันในรายงานอื่น บทนี้กำหนด Drawdown period เป็นยอดถึงจุดต่ำสุด และ Recovery period เป็นจุดต่ำสุดถึงยอดเดิม ช่วงที่ลึกที่สุดอาจไม่ใช่ช่วงที่นานที่สุด</p></section>`,
 'cumulative-lab':`<section class="lab" id="cumulative-comparison" aria-label="ผลตอบแทนสะสม EMA เทียบ S&P 500">${head('ภาพ · ผลตอบแทนสะสมเทียบตลาด','EMA 20/200 กับการถือ S&P 500 เติบโตต่างกันอย่างไร','เริ่มทั้งสองเส้นที่ 0% ก่อนลงทุนในวันเดียวกัน เลื่อนเลือกวันแล้วอ่านผลสะสมจากทุนเริ่มต้น รวมถึงส่วนต่างระหว่างสองพอร์ต')}<div class="controls two">${slider('cumulative-session','เลือกวันในกราฟผลตอบแทนสะสม',pm.periods,0,pm.periods,1,date(pm.periods),'เส้นสีม่วง = EMA 20/200 · เส้นประสีเขียว = S&P 500 ซื้อแล้วถือ')}</div><div class="lab-body">${chart('cumulative-chart',C.equity(r.dailyEquity,r.parameters.initialEquity,pm.periods,'cumulative'),'Cumulative Return EMA เทียบ S&P 500 ซื้อแล้วถือ')}<div id="cumulative-detail" class="month-detail"></div></div><div class="lab-actions"><button type="button" id="cumulative-start">ไปจุดเริ่มต้น</button><button type="button" id="cumulative-end">ไปวันสุดท้าย</button></div><p class="lab-foot">ใช้ราคาดัชนี ^GSPC ไม่รวมเงินปันผล พอร์ตทั้งสองหักต้นทุนตามอัตราเดียวกัน 0.10% ต่อด้าน แต่จำนวนคำสั่งต่างกัน จึงเป็นผลสุทธิของแบบจำลองซื้อแล้วถือ ไม่ใช่เส้นดัชนีดิบที่ไม่มีต้นทุน</p>${status('cumulative')}</section>`,
 'expectancy-lab':`<section class="lab" aria-label="ทดลองความสัมพันธ์ Win Rate Payoff Expectancy">${head('ภาพที่ 3 · ชนะบ่อยยังอาจขาดทุน','ต้องชนะเท่าไรจึงชดเชยขนาดขาดทุนได้',`ค่าตั้งต้นมาจากผล EMA ชุดเดียวกัน ลองลด Win Rate จาก ${p(t.winRate)} เป็น 10% โดยคงขนาดกำไรและขาดทุนเฉลี่ย แล้วอ่าน Expectancy ที่เปลี่ยนไป`)}<div class="controls">${slider('win-rate','Win Rate (%)',t.winRate*100,0,100,'any',p(t.winRate),'ที่เหลือเป็นเทรดแพ้ สมมติไม่มีเทรดเสมอ')}${slider('avg-win','กำไรเฉลี่ย (USD)',t.averageWin,1,Math.ceil(t.averageWin*3),'any',n(t.averageWin),'สุทธิหลังต้นทุนแล้ว')}${slider('avg-loss','ขาดทุนเฉลี่ย (USD)',t.averageLoss,1,Math.ceil(t.averageLoss*2),'any',n(t.averageLoss),'ใส่ขนาดเงินที่เสียเป็นค่าบวก')}</div><div class="lab-body"><div id="expectancy-chart" class="contribution-bars"></div></div><div id="win-results" class="readouts"></div><div id="win-explanation" class="lab-explanation"><p>ค่าฐาน: Win Rate ${p(t.winRate)} · Payoff ${n(t.payoffRatio,4)} · Expectancy ${signed(t.expectancy)} USD</p></div><div class="lab-actions"><button id="reset-win" type="button">กลับผล EMA ตั้งต้น</button></div><p class="lab-foot">ห้องนี้ทดลองความสัมพันธ์ในสูตร ไม่ได้รัน EMA ใหม่ ผลตอบแทนพอร์ตและรายงานส่วนอื่นจึงคงค่าเดิม ค่าเฉลี่ยที่ใช้เป็นผลย้อนหลัง ไม่ใช่ผลที่รับประกันในเทรดถัดไป</p>${status('win')}</section>`,
 'drawdown-lab':`<section class="lab" aria-label="เปรียบเทียบมูลค่าพอร์ตและ Drawdown">${head('ภาพที่ 4 · มูลค่าพอร์ตและระยะที่ต่ำกว่ายอด','พอร์ตติดลบจากทุน กับพอร์ตลดจากยอด เป็นคนละคำถาม',`เลื่อนไปวันที่ ${date(pm.maxDrawdownPeakIndex)} เพื่อดูยอดก่อน MDD แล้วเลือกวันที่ ${date(pm.maxDrawdownTroughIndex)} เพื่อดูจุดต่ำสุด กราฟล่างวัดจากยอดสูงสุดที่ผ่านมา ไม่ได้วัดจากเงินเริ่มต้น`)}<div class="controls two">${slider('session','เลือกวันซื้อขาย',pm.periods,0,pm.periods,1,date(pm.periods),'วัน 0 = เงินก่อนเริ่มลงทุน')}</div><div class="lab-body">${chart('equity-chart',C.equity(r.dailyEquity,r.parameters.initialEquity,pm.periods),'มูลค่าพอร์ต EMA เทียบซื้อแล้วถือ')}${chart('drawdown-chart',C.equity(r.dailyEquity,r.parameters.initialEquity,pm.periods,'drawdown'),'Drawdown รายวัน EMA เทียบซื้อแล้วถือ')}<div id="session-detail" class="month-detail"></div></div><div class="lab-actions"><button type="button" id="peak-day">ไปวันที่ยอดสูงสุด</button><button type="button" id="trough-day">ไปวันที่ต่ำสุด</button><button type="button" id="recovery-day">ไปวันที่ฟื้นถึงยอดเดิม</button><button type="button" id="last-day">ไปวันสุดท้าย</button></div><div class="lab-explanation"><p>EMA ลดจากยอดมากที่สุด ${p(pm.maxDrawdown,4)} เมื่อวัดสิ้นวัน ข้อมูลสิ้นวันไม่แสดงความเคลื่อนไหวระหว่างวันทั้งหมด ช่วง MDD กลับถึงยอดเดิมวันที่ ${date(pm.maxDrawdownRecoveryIndex)} หลังผ่านไป ${pm.peakToRecoveryPeriods} วันซื้อขาย</p></div><p class="lab-foot">เส้นทึบสีม่วง = EMA · เส้นประสีเขียว = ซื้อแล้วถือ · ทั้งสองใช้เวลา ทุนตั้งต้น และอัตราต้นทุนเดียวกัน ผลทดสอบอดีตไม่รับรองผลในอนาคต ดัชนีราคาไม่รวมเงินปันผล</p>${status('session')}</section>`,
 'risk-lab':`<section class="lab" aria-label="ผลตอบแทนรายวัน Sharpe และ Sortino">${head('ภาพที่ 5 · ผลตอบแทนแต่ละวัน','เปลี่ยนเกณฑ์ แล้วค่า Sharpe และ Sortino เปลี่ยนอย่างไร','เพิ่มอัตราปลอดความเสี่ยงเป็น 2% เพื่อดู Sharpe จากนั้นเพิ่มเป้าหมายขั้นต่ำเป็น 2% เพื่อดู Sortino กราฟผลตอบแทนพอร์ตยังเป็นข้อมูลเดิม')}<div class="controls two">${slider('rf','อัตราปลอดความเสี่ยง (% ต่อปี)',0,0,6,.25,'0.00%','ใช้เป็นเกณฑ์ใน Sharpe')}${slider('mar','เป้าหมายขั้นต่ำ MAR (% ต่อปี)',0,0,6,.25,'0.00%','ใช้เป็นเกณฑ์ใน Sortino')}</div><div class="lab-body">${chart('risk-chart',C.risk(pm.returns,0,r.dailyEquity.map(x=>x.date)),'ผลตอบแทนพอร์ตรายวันเทียบเป้าหมายขั้นต่ำ')}</div><div id="risk-results" class="readouts"></div><div id="risk-explanation" class="lab-explanation"><p>ใช้ผลตอบแทนทั้ง ${n(pm.periods,0)} วัน รวมวันถือเงินสด ค่าอัตราปลอดความเสี่ยงและ MAR ตั้งต้นเป็น 0%</p></div><div class="lab-actions"><button id="reset-risk" type="button">กลับเกณฑ์ 0%</button></div><p class="lab-foot">ตัวหารความผันผวนใช้ SD แบบตัวอย่าง (N−1) ส่วน Downside Deviation ใช้จำนวนวันทั้งหมด N ไม่ใช่เฉพาะวันที่ต่ำกว่าเป้าหมาย</p>${status('risk')}</section>`,
 'downloads':`<div class="download-list"><a href="robo-trade-performance-review.zip" download>ชุดไฟล์ทั้งหมด: ต้นฉบับ โค้ด และข้อมูล</a><a href="robo-trade-14.ipynb" download>Notebook: เรียนและรันทีละขั้น</a><a href="lesson_14.py" download>Python: ทดสอบจากราคาจริงและสร้างรายงาน</a><a href="performance-report.html">เปิดรายงานที่ Python สร้าง</a><a href="trades.csv" download>CSV: สมุดรายการซื้อขาย</a><a href="equity-daily.csv" download>CSV: มูลค่าพอร์ตรายวัน</a><a href="ema-bars.csv" download>CSV: ราคาและ EMA รายวัน</a><a href="data/sp500-daily.csv" download>CSV: ราคาจริงต้นทาง</a><a href="data/provenance.json" download>แหล่งข้อมูล วันที่ และ checksum</a></div>`,
 'review-questions':questions.map(([q,a])=>`<details class="review-question"><summary>${q}</summary><p>${a}</p></details>`).join('')
 };
};
