import React from 'react';
import {createRoot} from 'react-dom/client';
import '@fontsource/roboto/latin-400.css';
import '@fontsource/roboto/latin-500.css';
import '@fontsource/roboto/latin-700.css';
import '@fontsource/noto-sans-thai/thai-400.css';
import '@fontsource/noto-sans-thai/thai-500.css';
import '@fontsource/noto-sans-thai/thai-600.css';
import '@fontsource/noto-sans-thai/thai-700.css';
import '@fontsource/roboto-mono/latin-400.css';
import App from './App.jsx';
import './styles.css';
import '../book.css';
import './quantara.css';
import './field-guide.css';
import './book-shell.css';
createRoot(document.getElementById('root')).render(<App/>);
